version: '3'

services:
  app:
    build: .
    container_name: setoko_app
    restart: unless-stopped
    command: npm run start:dev
    ports:
      - 3030:3030
    networks:
      - setoko
    volumes:
      - ./:/usr/src/app
      # - /opt/app/node_modules/
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

  db:
    container_name: setoko_db
    restart: unless-stopped
    volumes:
      - setoko-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - setoko
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}

  redis:
    image: redis:alpine
    networks:
      - setoko

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - 8081:80
    networks:
      - setoko

volumes:
  setoko-data:

networks:
  setoko:
    name: setoko
    driver: bridge
