version: '3'

services:
  # app:
  #   build: .
  #   container_name: setoko_app
  #   restart: unless-stopped
  #   command: npm run start:dev
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - setoko
  #   volumes:
  #     - ./:/usr/src/app
  #     # - /opt/app/node_modules/
  #   environment:
  #     DATABASE_CLIENT: ${DATABASE_CLIENT}
  #     DATABASE_HOST: db
  #     DATABASE_PORT: ${DATABASE_PORT}
  #     DATABASE_NAME: ${DATABASE_NAME}
  #     DATABASE_USERNAME: ${DATABASE_USERNAME}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #     NODE_ENV: ${NODE_ENV}
  #   depends_on:
  #     - db

  db:
    container_name: setoko_db
    restart: unless-stopped
    volumes:
      - setoko-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - setoko
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - 8081:80
    networks:
      - setoko

volumes:
  setoko-data:

networks:
  setoko:
    name: setoko
    driver: bridge
