version: '3'

services:
  app:
    image: satyafariz/gotoko-test:latest
    container_name: gotoko-test_app
    restart: unless-stopped
    # command: "chmod +x /usr/src/app/run.sh && /usr/src/app/run.sh"
    ports:
      - 3030:3030
    networks:
      - gotoko
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DBNAME: app
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    depends_on:
      - db

  db:
    container_name: gotoko-test_db
    restart: unless-stopped
    # volumes:
    #   - gotoko-data-test:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - gotoko
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - 8081:80
    networks:
      - gotoko

volumes:
  gotoko-data-test:

networks:
  gotoko:
    name: gotoko
    driver: bridge
